name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install pyinstaller pillow

    - name: Build EXE with icon
      run: |
        pyinstaller --onefile --windowed --icon=app_icon.ico --hidden-import 'tkinter' --hidden-import 'pillow' --hidden-import 'os' --hidden-import 'PIL' newscript.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Steganographer-EXE
        path: dist/
